# Generated by Django 5.0.3 on 2024-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_feed_consecutive_update_fail_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="db_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="home_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="author_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="db_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="id",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
